stages:
  - signoff
  - static-analysis  # Static analyzers with scan-build and {OpenSSL,GnuTLS}
  - test-first       # Fedora Linux with gcc and {OpenSSL,GnuTLS}
  - test-rest        # Other Linux distros (CentOS7, CentOS8, Ubuntu18.04) and configurations (ibmtss; clang)
  - coverity         # Coverity on CentOS8 with OpenSSL/GnuTLS (run on 'coverity' branch only)
  - test-sanitizers  # Fedora Linux with gcc/ubsan and clang/asan
  - test-windows     # MingW32/64 builds
  - test-android     # Android

variables:
  BUILD_IMAGES_PROJECT: openconnect/build-images
  CENTOS7_BUILD: openconnect-cli-centos7
  CENTOS8_BUILD: openconnect-cli-centos8
  CENTOS9_BUILD: openconnect-cli-centos9
  FEDORA_BUILD: openconnect-cli-fedora38
  MINGW32_BUILD: openconnect-cli-mingw32
  MINGW64_BUILD: openconnect-cli-mingw64
  UBUNTU_BUILD: openconnect-cli-ubuntu
  ANDROID_BUILD: openconnect-cli-android
  ANDROID_TOOLCHAINDIR: /opt/android-sdk-linux_x86/toolchains

image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD

MinGW64/GnuTLS:
  stage: test-windows
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$MINGW64_BUILD
  script:
  - dnf remove -y wine.i686
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw64-configure --without-gnutls-version-check CFLAGS=-g
  - make -j4
# These tests seem to fail due to wine failing to start; setting as XFAIL
# since these never run before this patch set.
  - make VERBOSE=1 -j4 check XFAIL_TESTS="sigterm dtls-psk"
  tags:
  - shared
  except:
  - schedules
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - tests/*.log
      - openconnect-installer*.exe
